import { Poppins } from "next/font/google";
import "../app/style/globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
   weight: ["200","300","400","500","600","700","800"],
});

export const metadata = {
  title: "OneSchool",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
